# Generated by Django 5.0.6 on 2024-07-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_book_options_user_avatar_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sound', models.CharField(max_length=200)),
            ],
        ),
    ]
