# Generated by Django 5.0.6 on 2024-07-12 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_animaltestcase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnimalTestCase',
            new_name='Animal',
        ),
    ]
